### ISSUE TITLE
Jelly doesn't respond to window size

### ISSUE THREAD

**Issue by codymx** [lmgonzalves/jelly#3]
If a jelly is rendered at a desktop size and the window is scaled down, the canvas scales down okay with CSS, but if the page is reloaded, it seems to ignore it's bounding container and renders it at full size.

Larger screen: 
<img width="1319" alt="desktop" src="https://user-images.githubusercontent.com/22644154/43812709-86a420f4-9a90-11e8-90a9-176f8dff249c.png">

Smaller screen:
<img width="400" alt="mobile" src="https://user-images.githubusercontent.com/22644154/43812711-87efc53a-9a90-11e8-92b4-20af08ab183a.png">

This is my SVG code:

```
<svg width="2622px" height="640px" viewBox="0 0 2622 640" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none">
            <path d="M2024.35398,639.019917 L2024.35398,639.033416 C1680.6382,639.726285 1508.97788,639.352862 1509.37302,637.913146 C1404.97615,646.944218 1301.86397,600.073111 1216.24958,544.142572 C1195.09767,530.324423 1177.14613,512.71603 1155.35897,499.691946 C1122.14862,479.840319 1086.50928,463.245778 1049.52286,451.964382 C1006.83903,438.944552 962.110479,428.145267 917.396109,426.61102 C878.759173,425.285215 841.802535,431.956779 803.61226,436.345406 C740.723727,443.56998 665.167019,452.684713 607.129372,421.204288 C560.238413,395.770101 532.222097,345.901398 490.951984,312.09975 C405.645293,242.227698 291.148203,272.831816 191.169742,250.822034 C163.55613,244.741765 134.225352,232.619511 115.457058,210.59555 C99.1971579,191.513883 98.9532665,161.827194 74.0182061,149.875097 C54.9819146,140.751857 30.4297069,146.595325 13.967037,132.309244 C4.72185108,124.284933 4.62968281,113.896861 0,104.334049 L0,0.351165471 L1980,0.351165471 L1980,0 L2622,0 L2622,639.019917 L2024.35398,639.019917 Z" id="WAVE" fill="#DAF4EE"></path>
    </svg>
```

Is there any way it can get the size of it's bounding container and resize the contents inside the `<canvas>` accordingly? I feel like the fix is easy but I could be wrong. Thanks!

**Comment by lmgonzalves** [comment]
Can you reproduce the issue in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/)?

**Comment by codymx** [comment]
@lmgonzalves Yes! You can find it here: https://codepen.io/c0mrx/pen/oMmbNx

I think a possible fix is to get the coordinates from the SVG path, get the size of the `<canvas>` and map out the coordinates relative to the containers size instead of the exact pixel dimensions of the SVG path.

I'm not very experienced with `<canvas>`, but this could also maybe be done using `ctx.scale()`.

Of course, I guess this is more of a feature request than an actual issue. Great work!

**Comment by lmgonzalves** [comment]
Thanks! I can see the problem.

A similar issue happens to me when I wanted to make the [Jellyfish Slider](https://lmgonzalves.github.io/jelly/jellyfish.html) responsive.
Please take a look at the [code](https://github.com/lmgonzalves/jelly/blob/1706f327a271ac0bf2d9800c9ec7e2fc9a118019/js/jellyfish.js#L153-L168) I've used there to solve the issue.

I would like to keep the library working with real coordinates instead map out the coordinates relative to the containers.

**Comment by codymx** [comment]
@lmgonzalves I see! this should work for what I'm using it for. 

Thanks for the prompt response! I appreciate the help.
