### ISSUE TITLE
es6 import use

### ISSUE THREAD

**Issue by mejuliver** [lmgonzalves/jelly#6]
I'm trying to utilize the plugin by

```
import $ from 'jquery';
import 'Jelly';

$(function(){
     var options = {
        paths: '#circle-path',     // Shape we want to draw
        pointsNumber: 25,            // Number of points
        maxDistance: 4,             // Max distance among points
        color: '#ff0019',
        opacity: 0.27,
        // centroid: '.centroid-text'   // Element to move accordingly with the centroid of the shape
        // debug: true               // Uncomment this to see the points
     };

    var jelly =Jelly('.jelly-canvas', options);

});
```

but i get this error instead

> Uncaught ReferenceError: Jelly is not defined

any help, ideas please?

**Comment by lmgonzalves** [comment]
Please try the following:

1. Install the package from `npm`:

```bash
npm install jelly.js
```

2. Import it anywhere, like this:

```js
import Jelly from 'jelly.js';
```

It should work as expected, but please let me know.

**Comment by mejuliver** [comment]
tried it

`import Jelly from 'jelly.js';`

then

`var jelly = Jelly('.jelly-canvas', options);`

or even

`var jelly = new Jelly('.jelly-canvas', options);`

but unfortunately, not working, returns

> Uncaught TypeError: Cannot read property 'getContext' of null

any ideas, help please?

**Comment by lmgonzalves** [comment]
Ok, that is a different error, that is probably caused because the `canvas` element is not found.
Can you reproduce the issue on [jsfiddle](http://jsfiddle.net) or [codesandbox](https://codesandbox.io/), so I can take a better look and help more?

**Comment by mejuliver** [comment]
Its been resolved, you are correct, simply the element does not exit, thank you for your help. Great plugin!

**Comment by lmgonzalves** [comment]
Great! :)
