### ISSUE TITLE
Image Resizing/Repositioning within the options variable

### ISSUE THREAD

**Issue by benholness-minty** [lmgonzalves/jelly#7]
Hi @lmgonzalves,

Thankyou for creating this library, we've been looking for something like this and its amazing.

I'm relatively new to learning how canvas works and was just wondering about whether jelly.js supports image resizing or am I missing something. I've created a codepen showing the kind of thing I've been doing, but as you can see the images are larger than the clipped area. https://codepen.io/ben-holness/pen/RwWrdxN?editors=0100

Is image resizing/repositioning functionality built into the library or should I be using the canvas or call other Javascript methods to accomplish this?

**Comment by lmgonzalves** [comment]
Hi, and thanks for the kind words!
Well, we have no option for resizing the image in the canvas at the moment. You have to do it yourself, but I think it is not difficult at all.
It could be added to the library, but I don't have the time (Pull Request are welcome).
Good luck!

**Comment by benholness-minty** [comment]
No worries! Thanks for the speedy response.
